# -*- coding: utf-8 -*-
"""Английский перевод надписей передатчика и приёмника.
Слева — надпись в точности как в исходниках (между кавычками, со всеми «\\n» и пробелами), справа — перевод.
Из этого списка tools/make_lang.py делает hearlink/lang_en.h и проверяет, что переведено всё, что есть в исходниках.
Название церкви «ВІДРОДЖЕННЯ» в заставке и шапке не переводится (это имя), буквы экранной клавиатуры — тоже."""

PAIRS = [
    # ---- списки вариантов
    (r"Сама", r"Auto"),
    (r"24 Мбіт/с", r"24 Mbit/s"), (r"18 Мбіт/с", r"18 Mbit/s"), (r"12 Мбіт/с", r"12 Mbit/s"), (r"6 Мбіт/с", r"6 Mbit/s"),
    (r"11 Мбіт/с", r"11 Mbit/s"), (r"5,5 Мбіт/с", r"5.5 Mbit/s"), (r"2 Мбіт/с", r"2 Mbit/s"), (r"1 Мбіт/с", r"1 Mbit/s"),
    (r"0,5 Мбіт/с", r"0.5 Mbit/s"),
    (r"Найвища — без стиснення", r"Highest — uncompressed"),
    (r"Стандартна — зі стисненням", r"Standard — compressed"),
    (r"Мова — лише смуга голосу", r"Speech — voice band only"),
    (r"Дальня — для слабкого сигналу", r"Long range — for weak signal"),
    (r"найвища", r"highest"), (r"стандартна", r"standard"), (r"мова", r"speech"), (r"дальня", r"long range"),
    (r"По черзі", r"In turn"), (r"Мелодія 1", r"Tune 1"), (r"Мелодія 2", r"Tune 2"),
    (r"Моно", r"Mono"), (r"Стерео", r"Stereo"),
    (r"Вбудований вхід", r"Built-in input"), (r"Модуль PCM1808", r"PCM1808 module"),
    (r"Не міняти — лишатись на своєму каналі", r"Don't change — stay on my channel"),
    (r"Міняти самому на вільніший", r"Move to a freer channel automatically"),
    (r"Вимкнено — іде звук із входу", r"Off — the input is on air"),
    (r"Тон 1000 Гц", r"1000 Hz tone"),
    (r"Голос: «Увага! Йде перевірка звуку»", r"Voice: «Attention please! Sound check»"),
    (r"Голос і музика по колу", r"Voice and music in a loop"),
    (r"Музика", r"Music"),
    (r"Музика, голос поверх", r"Music with voice over it"),
    (r"Канали: лівий — гудок, правий — два", r"Channels: left — one beep, right — two"),
    (r"тон", r"tone"), (r"голос", r"voice"), (r"голос+музика", r"voice+music"), (r"музика", r"music"),
    (r"музика+голос", r"music+voice"), (r"канали", r"channels"), (r"вимкнено", r"off"),
    (r"голос і музика", r"voice and music"), (r"музика з голосом", r"music with voice"), (r"перевірка каналів", r"channel check"),
    (r"Ніколи", r"Never"), (r"Через 1 хвилину", r"After 1 minute"), (r"Через 5 хвилин", r"After 5 minutes"),
    (r"Через 15 хвилин", r"After 15 minutes"),
    (r"вбудований", r"built-in"), (r"ніколи", r"never"), (r"1 хв", r"1 min"), (r"5 хв", r"5 min"), (r"15 хв", r"15 min"),
    # ---- настройки и пояснения
    (r"Канал", r"Channel"),
    (r"Радіоканал, на якому йде передача. Приймачі знаходять його самі. Якщо звук переривається — спробуйте інший або «Знайти вільний канал».",
     r"The radio channel used for transmission. Receivers find it by themselves. If the sound breaks up, try another one or «Find a free channel»."),
    (r"Набір", r"Kit"),
    (r"Номер вашого комплекту. Приймачі отримують його від передавача самі. Міняйте, якщо поруч працює ще один такий набір.",
     r"The number of your set. Receivers get it from the transmitter by themselves. Change it if another such set works nearby."),
    (r"Швидкість радіо", r"Radio rate"),
    (r"Найнадійніше — 5,5 Мбіт/с і нижче: що менша швидкість, то далі чути. На 6–24 Мбіт/с пакети губляться навіть поруч із приймачем — не радимо. Для 2 Мбіт/с і нижче передавач сам знизить якість звуку. «Сама» — обирає від 5,5 униз за сигналом приймачів.",
     r"5.5 Mbit/s and lower is the most reliable: the lower the rate, the longer the range. At 6–24 Mbit/s packets get lost even next to a receiver — not recommended. For 2 Mbit/s and lower the transmitter lowers the sound quality itself. «Auto» picks from 5.5 downwards by the receivers' signal."),
    (r"Потужність", r"Power"),
    (r"Сила сигналу передавача. У малому залі можна зменшити — менше завад сусідам.",
     r"Transmitter signal strength. In a small hall you can reduce it — less interference for neighbours."),
    (r" дБм", r" dBm"),
    (r"Підсилення входу", r"Input gain"),
    (r"Додає гучності тихому джерелу. Краще виставити рівень на пульті, а тут лишити 0.",
     r"Adds volume to a quiet source. It is better to set the level on the mixer and leave 0 here."),
    (r" дБ", r" dB"),
    (r"Вхід з пульта", r"Mixer input"),
    (r"Яким входом передавач приймає звук з пульта. Вбудований вхід працює одразу; модуль PCM1808 дає чистіший звук і стерео, але його треба під'єднати.",
     r"Which input takes the sound from the mixer. The built-in input works right away; the PCM1808 module gives cleaner sound and stereo, but it has to be connected."),
    (r"Перевірочний звук", r"Test sound"),
    (r"Замість входу в ефір іде голос, музика або тон — щоб перевірити приймачі без пульта. «Канали» — перевірка стерео: один гудок ліворуч, два праворуч.",
     r"Voice, music or a tone goes on air instead of the input — to check receivers without a mixer. «Channels» checks stereo: one beep on the left, two on the right."),
    (r"Яскравість екрана", r"Screen brightness"),
    (r"Яскравість підсвітки цього екрана.", r"Backlight brightness of this screen."),
    (r"Гасити екран", r"Dim the screen"),
    (r"Через який час без дотиків екран пригасне. Передача при цьому триває. Дотик повертає яскравість.",
     r"How long without touches before the screen dims. Transmission goes on. A touch brings the brightness back."),
    (r"Якість звуку", r"Sound quality"),
    (r"Що нижча якість, то менший потік: пакети рідші, запасні копії перекривають довшу заваду, і працюють повільні, далекобійні швидкості радіо. Плата — затримка: пакет триває 2, 4, 8 або 12 мс.",
     r"The lower the quality, the smaller the stream: packets are rarer, spare copies cover longer interference, and slow long-range radio rates work. The price is delay: a packet lasts 2, 4, 8 or 12 ms."),
    (r"Мелодія", r"Tune"),
    (r"Яку мелодію грати в режимах із музикою. «По черзі» — одна за одною.",
     r"Which tune to play in modes with music. «In turn» — one after another."),
    (r"Оголошення кожні", r"Announcement every"),
    (r"Як часто в режимі «Музика, голос поверх» музика стихає і звучить голос.",
     r"How often the music fades and the voice sounds in «Music with voice over it» mode."),
    (r" с", r" s"),
    (r"Музика під голосом", r"Music under the voice"),
    (r"Наскільки тихішою стає музика, поки говорить голос. −16 дБ — добре чути і голос, і музику; −40 дБ — музики майже не чути.",
     r"How much quieter the music gets while the voice speaks. −16 dB — both voice and music are heard well; −40 dB — music is almost inaudible."),
    (r"Повтор голосу через", r"Repeat the voice after"),
    (r"Пауза між повторами оголошення в режимі «Голос».", r"Pause between announcement repeats in «Voice» mode."),
    (r"Гучність музики", r"Music volume"),
    (r"Гучність мелодій у перевірочному звуці. 0 дБ — як записано.", r"Volume of tunes in the test sound. 0 dB — as recorded."),
    (r"Гучність голосу", r"Voice volume"),
    (r"Гучність оголошення в перевірочному звуці. 0 дБ — як записано.", r"Volume of the announcement in the test sound. 0 dB — as recorded."),
    (r"Ефір", r"Air"),
    (r"Стерео йде в ефір, коли джерело стереофонічне: мелодії перевірки або модуль PCM1808. Приймач грає стерео, якщо його вихід — «два канали» (навушники напряму); у «протифазі» (для підсилювача) — моно. У якості «дальня» завжди моно.",
     r"Stereo goes on air when the source is stereo: test tunes or the PCM1808 module. A receiver plays stereo if its output is «two channels» (headphones directly); in «antiphase» (for an amplifier) — mono. «Long range» quality is always mono."),
    (r"Канал при заторі", r"On congestion"),
    (r"Коли ефір на каналі зайнятий так, що пакети довго чекають (звук рветься), передавач сам замовкає на дві секунди, міряє всі канали й переходить на вільніший. Приймачі знаходять його самі. Про перехід і причину буде повідомлення.",
     r"When the channel is so busy that packets wait long (the sound breaks up), the transmitter moves to a freer channel by itself — together with the receivers, without a pause. You will see a message about the move and its reason."),
    (r"Мова / Language", r"Мова / Language"),
    (r"Мова написів на передавачі й на приймачах та голос оголошення в перевірочному звуці. Language of the transmitter and receivers and the voice of the test announcement.",
     r"Мова написів на передавачі й на приймачах та голос оголошення в перевірочному звуці. Language of the transmitter and receivers and the voice of the test announcement."),
    (r"сама (%s)", r"auto (%s)"), (r"%s Мбіт/с", r"%s Mbit/s"), (r"сама", r"auto"),
    (r"%s — за швидкістю", r"%s — due to rate"),
    (r"сам", r"auto"), (r"ні", r"no"),
    (r"стерео (зараз моно)", r"stereo (mono now)"), (r"стерео", r"stereo"), (r"моно", r"mono"), (r"по черзі", r"in turn"),
    (r"%s%d дБ", r"%s%d dB"),
    # ---- справка
    (r"Як підключити звук", r"How to connect the sound"),
    (r"Звук беруть із лінійного виходу пульта (AUX, MONITOR або REC OUT) — не з виходу на колонки.\n",
     r"Take the sound from a line output of the mixer (AUX, MONITOR or REC OUT) — not from the speaker output.\n"),
    (r"Між пультом і передавачем ставте розв'язку (ізолятор «земляної петлі»): без неї може гудіти.\n",
     r"Put an isolator (ground loop isolator) between the mixer and the transmitter: without it there may be hum.\n"),
    (r"Після підключення дивіться на сторінку «Головна»: смужка рівня має рухатись у такт звуку.",
     r"After connecting, look at the «Home» page: the level bar should move with the sound."),
    (r"Рівень входу", r"Input level"),
    (r"Смужка на головній сторінці показує гучність на вході.\n", r"The bar on the home page shows the input loudness.\n"),
    (r"Зелена зона — добре. Жовта — гучно, але ще чисто. Червона — перевантаження: звук у навушниках хрипить.\n",
     r"Green zone — good. Yellow — loud but still clean. Red — overload: the sound in headphones is distorted.\n"),
    (r"Рівень виставляють на пульті так, щоб найгучніші місця доходили до жовтої зони, але не до червоної.\n",
     r"Set the level on the mixer so that the loudest moments reach the yellow zone but not the red one.\n"),
    (r"Якщо джерело тихе і на пульті додати нічим — додайте «Підсилення входу» на сторінці «Звук».",
     r"If the source is quiet and the mixer cannot add more — add «Input gain» on the «Sound» page."),
    (r"Канал і набір", r"Channel and kit"),
    (r"Канал — це «доріжка» в ефірі Wi-Fi. Передавач сидить на одному каналі, приймачі знаходять його самі.\n",
     r"A channel is a «lane» in the Wi-Fi air. The transmitter stays on one channel, receivers find it by themselves.\n"),
    (r"Якщо звук у навушниках переривається, на сторінці «Ефір» натисніть «Знайти вільний канал»: передавач за дві секунди перевірить усі канали й стане на найвільніший.\n",
     r"If the sound in headphones breaks up, press «Find a free channel» on the «Air» page: in two seconds the transmitter checks all channels and takes the freest one.\n"),
    (r"Коли ефір зайнятий надовго, передавач сам переходить на вільніший канал і пише про це на екрані (вимикається там само: «Канал при заторі»).\n",
     r"When the air stays busy, the transmitter moves to a freer channel by itself and says so on the screen (can be switched off there: «On congestion»).\n"),
    (r"Набір — номер вашого комплекту; приймачі отримують його від передавача самі. Якщо поруч працює другий такий комплект, дайте їм різні номери.",
     r"Kit is the number of your set; receivers get it from the transmitter by themselves. If a second such set works nearby, give them different numbers."),
    (r"Приймачі", r"Receivers"),
    (r"Новий приймач треба додати до набору: «Приймачі» › «Додати приймач», звірити код і дозволити. Далі він сам знаходить передавач. Чужий приймач звуку не почує.\n",
     r"A new receiver has to be added to the kit: «Receivers» › «Add receiver», compare the code and allow. After that it finds the transmitter by itself. A foreign receiver will not hear the sound.\n"),
    (r"Ручка — гучність. Натиск на ручку — тиша. Довгий натиск — меню приймача, у меню довгий натиск — назад.\n",
     r"Knob — volume. Press the knob — mute. Long press — receiver menu; in the menu a long press goes back.\n"),
    (r"Без сигналу приймач за 10 секунд засинає і прокидається сам, коли передавач з'явиться. Видалити приймач — у його вікні «Видалити з набору».",
     r"Without a signal a receiver falls asleep in 10 seconds and wakes up by itself when the transmitter appears. To remove a receiver use «Remove from kit» in its window."),
    (r"Запис на картку", r"Recording to card"),
    (r"Якщо в передавачі є картка пам'яті, усе, що йде в ефір, можна записувати у файл WAV.\n",
     r"If there is a memory card in the transmitter, everything on air can be recorded to a WAV file.\n"),
    (r"Кнопка запису — на сторінці «Головна». Година запису займає близько 230 МБ.\n",
     r"The record button is on the «Home» page. One hour of recording takes about 230 MB.\n"),
    (r"Картка — microSD з розміткою FAT32; exFAT передавач не читає. «Картка не відповідає» — її немає або немає контакту.\n",
     r"The card must be a microSD formatted as FAT32; the transmitter does not read exFAT. «Card does not respond» means there is no card or no contact.\n"),
    (r"Перед тим як виймати картку, зупиніть запис.\n", r"Stop the recording before removing the card.\n"),
    (r"«Файли» поруч із кнопкою запису відкривають картку: теки й файли, пуск файлу в ефір (WAV або MP3), копіювання, видалення, нова тека, форматування.",
     r"«Files» next to the record button opens the card: folders and files, putting a file on air (WAV or MP3), copying, deleting, new folder, formatting."),
    # --- файловый менеджер карты
    (r"Файл", r"File"), (r"Файли", r"Files"), (r"місця немає", r"no space"), (r"Рівень звуку з файлу", r"File sound level"),
    (r"Назва нової теки", r"New folder name"),
    (r"%u Б", r"%u B"), (r"%u,%u МБ", r"%u.%u MB"), (r"%u МБ", r"%u MB"),
    (r"%u год %u хв", r"%u h %u min"), (r"%u хв %u с", r"%u min %u s"), (r"%u с", r"%u s"),
    (r"Нова тека", r"New folder"), (r"Інше", r"More"), (r"Вставити сюди", r"Paste here"), (r"Зупинити", r"Stop"), (r"В ефір", r"On air"),
    (r"Копіювати", r"Copy"), (r"Переглянути", r"View"), (r"Видалити", r"Delete"), (r"Далі", r"Next"), (r"Стерти все", r"Erase all"),
    (r"Оновити список", r"Refresh list"), (r"Видалити цю теку", r"Delete this folder"), (r"Форматувати картку", r"Format card"),
    (r"Копіюється «%s». Відкрийте теку й натисніть «Вставити сюди».", r"Copying «%s». Open a folder and press «Paste here»."),
    (r"Торкніться файлу: пустити в ефір, скопіювати, видалити. Тека відкривається дотиком.",
     r"Tap a file to put it on air, copy or delete it. Tap a folder to open it."),
    (r"Картка пам'яті", r"Memory card"), (r"вільно %u МБ з %u МБ", r"%u MB free of %u MB"),
    (r"Не вдалося прочитати теку", r"Could not read the folder"), (r"Читаю картку…", r"Reading the card…"), (r"Тека порожня", r"The folder is empty"),
    (r"записів: %d", r"items: %d"), (r"ще %d не показано", r"%d more not shown"),
    (r"Звук WAV", r"WAV sound"), (r"Звук MP3", r"MP3 sound"), (r"Текст", r"Text"), (r"Читаю файл…", r"Reading the file…"),
    (r"%u кбіт/с", r"%u kbit/s"), (r"%u біт", r"%u bit"), (r"кГц", r"kHz"), (r"Зараз в ефірі", r"On air now"),
    (r"Такий запис в ефір не піде: потрібен MP3 або WAV (звичайний, не стиснений).", r"This recording cannot go on air: an MP3 or a plain (uncompressed) WAV is needed."), (r"Звук", r"Sound"),
    (r"Файл пошкоджено, або це не той запис, яким він названий.", r"The file is damaged or is not what its name says."),
    (r"Це не звук — в ефір його пустити не можна.", r"This is not sound — it cannot be put on air."),
    (r"Файл порожній", r"The file is empty"), (r"Інші дії", r"More actions"),
    (r"Видалити файл?", r"Delete the file?"), (r"Видалити теку?", r"Delete the folder?"), (r"Форматувати картку?", r"Format the card?"),
    (r"Точно стерти все?", r"Really erase everything?"),
    (r"«%s» буде стерто з картки назавжди.", r"«%s» will be erased from the card for good."),
    (r"Теку «%s» буде стерто разом з усім, що в ній (записів: %d).", r"Folder «%s» will be erased with everything in it (items: %d)."),
    (r"Усі файли й теки на картці буде стерто назавжди. Картка отримає розмітку FAT32.", r"All files and folders on the card will be erased for good. The card will be formatted as FAT32."),
    (r"На картці зайнято %u МБ. Після форматування повернути файли не вдасться.", r"%u MB are used on the card. After formatting the files cannot be recovered."),
    (r"Копіюю…", r"Copying…"), (r"Видаляю…", r"Deleting…"), (r"Форматую картку…", r"Formatting the card…"), (r"Працюю з карткою…", r"Working with the card…"),
    (r"Це триває до хвилини. Не вимикайте передавач і не виймайте картку.", r"This takes up to a minute. Do not switch the transmitter off or remove the card."),
    (r"Картка зайнята — спробуйте ще раз", r"The card is busy — try again"), (r"Надто довгий шлях", r"The path is too long"),
    (r"Файл пішов в ефір", r"The file is on air"), (r"Картки немає", r"No card"), (r"На картці не вистачає місця", r"Not enough space on the card"),
    (r"Файл зараз в ефірі або записується", r"The file is on air or being recorded now"), (r"Скасовано", r"Cancelled"),
    (r"Така назва не годиться або вже зайнята", r"This name is not suitable or already taken"), (r"Надто багато вкладених тек", r"Too many nested folders"),
    (r"Спершу зупиніть запис", r"Stop the recording first"), (r"Не вдалося — картка не відповіла", r"Failed — the card did not respond"),
    (r"Картку пам'яті вийнято", r"The memory card was removed"), (r"Скопійовано", r"Copied"), (r"Теку створено", r"Folder created"),
    (r"Картку відформатовано", r"Card formatted"), (r"Видалено", r"Deleted"),
    (r"Файл доіграв — в ефірі знову звук джерела", r"The file has finished — the source is on air again"),
    (r"Файл не читається — в ефірі знову звук джерела", r"The file cannot be read — the source is on air again"),
    (r"%s не читається: треба FAT32", r"%s unreadable: FAT32 needed"), (r"розмітка", r"format"),
    (r"картка не запускається", r"card does not start"), (r"картка не відповідає", r"card does not respond"),
    (r"не та розмітка", r"wrong format"), (r" (ЗНАКУ ПОЧАТКУ КАДРУ НЕМАЄ)", r" (NO FRAME START SIGNAL)"), (r"свій (сторінки зсуває екран)", r"own (the screen shifts pages)"), (r"ДРАЙВЕРА (без руху сторінок)", r"DRIVER'S (pages do not move)"), (r"не запускається", r"does not start"), (r"не відповідає", r"does not respond"),
    (r"Якщо щось не так", r"If something is wrong"),
    (r"Тиша в навушниках: перевірте смужку рівня на «Головній». Якщо вона стоїть — звук не доходить від пульта.\n",
     r"Silence in headphones: check the level bar on «Home». If it does not move — the sound does not arrive from the mixer.\n"),
    (r"Для перевірки без пульта ввімкніть «Перевірочний звук» на сторінці «Звук» — у навушниках буде голос і музика.\n",
     r"To check without a mixer turn on «Test sound» on the «Sound» page — there will be voice and music in headphones.\n"),
    (r"Звук переривається: «Ефір» › «Знайти вільний канал»; поставте передавач вище, ближче до людей.\n",
     r"The sound breaks up: «Air» › «Find a free channel»; put the transmitter higher, closer to the people.\n"),
    (r"Не допомогло — на сторінці «Звук» знизьте «Якість звуку»: передача стане стійкішою, а на «Ефірі» можна буде взяти меншу швидкість радіо.\n",
     r"Did not help — lower «Sound quality» on the «Sound» page: transmission becomes more robust, and a lower radio rate can be chosen on «Air».\n"),
    (r"Хрипить: рівень у червоній зоні — зменшіть на пульті.", r"Distorted: the level is in the red zone — reduce it on the mixer."),
    # ---- шапка, вкладки, главная
    (r"В ЕФІРІ", r"ON AIR"), (r"ПЕРЕВАНТАЖЕННЯ", r"OVERLOAD"), (r"ТИХО НА ВХОДІ", r"INPUT SILENT"), (r"ПЕРЕВІРКА ЗВУКУ", r"SOUND CHECK"),
    (r"РАДІО МОВЧИТЬ", r"RADIO SILENT"), (r"ТИША В ЕФІРІ", r"MUTED ON AIR"),
    (r"передавач звуку", r"sound transmitter"), (r"приймачі", r"receivers"), (r"звук на вході", r"input sound"),
    (r"радіоефір", r"radio air"), (r"налаштування", r"settings"), (r"довідка", r"help"),
    (r"Головна", r"Home"), (r"Звук", r"Sound"), (r"Налашт.", r"Settings"), (r"Довідка", r"Help"),
    (r"Який звук", r"Which sound"),
    (r"Записати", r"Record"), (r"так", r"yes"), (r"Екран", r"Screen"), (r"вимкнути", r"turn off"), (r"Налагодження ефіром", r"Debug over air"),
    (r"Рядки порту всіх пристроїв набору видно в порту того, що підключений до комп'ютера; команди іншим пристроям — теж ефіром. Для налагодження без дротів до приймачів.",
     r"Port output of every device in the kit is shown on the one connected to a computer; commands to other devices also go over the air. For debugging without wires to receivers."),
    (r"відмінний", r"excellent"), (r"добрий", r"good"), (r"слабкий", r"weak"), (r"дуже слабкий", r"very weak"),
    (r"не на зв'язку", r"offline"),
    (r"спить · вимкнений з передавача", r"asleep · turned off from here"),
    (r"вимкнений з передавача", r"turned off from here"),
    (r"прокидається…", r"waking up…"),
    (r"сигнал %s · гучність %d %%%s", r"signal %s · volume %d %%%s"),
    (r" · тиша", r" · muted"),
    (r"З пульта", r"Mixer"), (r"Перевірка", r"Test"), (r"ТИША", r"MUTE"), (r"Тиша", r"Mute"),
    (r"з %d", r"of %d"),
    (r"+ Додати", r"+ Add"),
    (r"Вимкнути передавач", r"Turn the transmitter off"),
    (r"Шукаю…", r"Searching…"),
    (r"Знайти вільний канал", r"Find a free channel"),
    (r"Стан і про пристрій", r"Status and about"),
    (r"Перезапустити", r"Restart"),
    (r"Скинути все", r"Reset all"),
    (r"« Теми", r"« Topics"),
    (r"тихо", r"quiet"),
    (r"%d дБ", r"%d dB"),
    (r"Звуку на вході немає", r"No sound at the input"),
    (r"Рівень добрий", r"Level is good"),
    (r"Гучно, але ще чисто", r"Loud but still clean"),
    (r"Перевантаження — зменшіть рівень на пульті", r"Overload — reduce the level on the mixer"),
    (r"Іде перевірочний звук, вхід вимкнено", r"Test sound is on, the input is off"),
    (r"Тиша в ефірі: приймачі нічого не чують", r"Muted on air: receivers hear nothing"),
    (r"вільно %u год", r"%u h free"), (r"вільно %u хв", r"%u min free"),
    (r"%d з %d", r"%d of %d"),
    (r"Рівень перевірочного звуку", r"Test sound level"),
    (r"Приймачів у наборі ще немає", r"No receivers in the kit yet"),
    (r"Натисніть «+ Додати» і ввімкніть приймач —", r"Press «+ Add» and switch a receiver on —"),
    (r"він попросить доступ. Чужий приймач звуку не почує.", r"it will ask for access. A foreign receiver hears nothing."),
    (r"Спектр входу", r"Input spectrum"),
    (r"100 Гц … 12 кГц", r"100 Hz … 12 kHz"),
    (r"Зайнятість каналів", r"Channel occupancy"),
    (r"сам змінив канал з %u на %u, %u хв тому", r"moved from channel %u to %u, %u min ago"),
    (r"затор, вільнішого не знайшов, %u хв тому", r"congestion, no freer channel, %u min ago"),
    (r"нижче — вільніше", r"lower is freer"),
    (r"ще не вимірювалось", r"not measured yet"),
    (r"Режим", r"Mode"),
    # ---- окна
    (r"Ні", r"No"), (r"Скасувати", r"Cancel"), (r"Так", r"Yes"), (r"Закрити", r"Close"), (r"Готово", r"Done"),
    (r"Версія програми", r"Firmware version"), (r"Адреса пристрою", r"Device address"), (r"Працює", r"Uptime"),
    (r"%u за секунду", r"%u per second"), (r"Пакетів в ефір", r"Packets on air"),
    (r"%.1f мс, найдовше %.0f мс", r"%.1f ms, longest %.0f ms"), (r"Очікування ефіру", r"Waiting for air"),
    (r"Відмов / перезапусків радіо", r"Refusals / radio restarts"),
    (r"%u КБ", r"%u KB"), (r"Вільної пам'яті", r"Free memory"),
    (r"на зв'язку", r"online"),
    (r"Сигнал", r"Signal"), (r"%d дБм, %s", r"%d dBm, %s"), (r", тиша", r", muted"),
    (r"Гучність", r"Volume"),
    (r"%.1f %% пакетів", r"%.1f %% of packets"), (r"Втрати", r"Loss"),
    (r"%u мс", r"%u ms"), (r"Запас (затримка)", r"Buffer (delay)"),
    (r"Вихід звуку", r"Audio output"),
    (r"протифаза (стара версія)", r"antiphase (old version)"),
    (r"два канали (навушники)", r"two channels (headphones)"),
    (r"протифаза (підсилювач)", r"antiphase (amplifier)"),
    (r"%u год %02u хв, версія %.1f", r"%u h %02u min, version %.1f"),
    (r"Показати себе", r"Identify"), (r"Перейменувати", r"Rename"), (r"Тихіше", r"Quieter"), (r"Гучніше", r"Louder"),
    (r"Увімкнути", r"Turn on"), (r"Вимкнути", r"Turn off"),
    (r"Вихід: протифаза", r"Output: antiphase"), (r"Вихід: два канали", r"Output: two channels"),
    (r"Видалити з набору", r"Remove from kit"),
    (r"Дозволити", r"Allow"),
    (r"Додати приймач", r"Add receiver"),
    (r"Увімкніть новий приймач поруч — він попросить доступ.", r"Switch a new receiver on nearby — it will ask for access."),
    (r"Звірте код із кодом на екрані приймача і дозвольте.", r"Compare the code with the one on its screen and allow."),
    (r"Без дозволу приймач звуку не почує.", r"Without permission a receiver hears nothing."),
    (r"Чекаю на приймач…", r"Waiting for a receiver…"),
    (r"код %04u", r"code %04u"),
    (r"абв", r"abc"),
    (r"Ім'я приймача", r"Receiver name"),
    (r"до %d літер", r"up to %d letters"),
    (r"Знайти вільний канал?", r"Find a free channel?"), (r"Перезапустити?", r"Restart?"),
    (r"Скинути всі налаштування?", r"Reset all settings?"), (r"Зупинити запис?", r"Stop recording?"),
    (r"Вимкнути передавач?", r"Turn the transmitter off?"), (r"Видалити приймач з набору?", r"Remove the receiver from the kit?"),
    (r"Увімкнути перевірочний звук?", r"Turn the test sound on?"),
    (r"Передавач за дві секунди перевірить усі канали й стане на найвільніший. На цей час звук у навушниках зникне, потім приймачі самі знайдуть новий канал.",
     r"In two seconds the transmitter checks all channels and takes the freest one. The sound in headphones disappears for that time, then receivers find the new channel by themselves."),
    (r"Передача перерветься на кілька секунд.", r"Transmission will stop for a few seconds."),
    (r"Канал, набір, гучність входу та інші налаштування повернуться до початкових. Пристрій перезапуститься.",
     r"Channel, kit, input gain and other settings return to defaults. The device restarts."),
    (r"Файл буде збережено на картці.", r"The file will be saved on the card."),
    (r"Передача припиниться, екран згасне, усе засне. Щоб увімкнути знову — торкніться екрана.",
     r"Transmission stops, the screen goes dark, everything sleeps. Touch the screen to turn it on again."),
    (r"Приймач втратить доступ до звуку: ключ набору зміниться й сам дійде до інших приймачів. Повернути його можна через «Додати приймач».",
     r"The receiver loses access to the sound: the kit key changes and reaches the other receivers by itself. It can be returned via «Add receiver»."),
    (r"Замість звуку з джерела в ефір піде перевірочний звук. Повернути — ліва кнопка у цьому ряду.",
     r"The test sound goes on air instead of the source sound. To return — the left button in this row."),
    (r"Назва джерела звуку", r"Sound source name"),
    (r"Доступ дозволено — приймач з'явиться у списку", r"Access allowed — the receiver will appear in the list"),
    (r"Церква «Відродження»", r"Vidrodzhennia Church"),
    (r"передавач звуку для слабочуючих", r"sound transmitter for the hard of hearing"),
    (r"версія %s", r"version %s"),
    (r"Передавач вимкнено", r"The transmitter is off"),
    (r"Торкніться екрана, щоб увімкнути", r"Touch the screen to turn it on"),
    (r"Ефір на каналі %u зайнятий", r"Channel %u is busy"),
    (r"Пакети чекали до %u мс. Шукаю вільніший канал — 2 с тиші", r"Packets waited up to %u ms. Looking for a freer channel — 2 s of silence"),
    (r"Канал змінено: з %u на %u", r"Channel changed: from %u to %u"),
    (r"Причина: ефір був зайнятий, пакети чекали до %u мс", r"Reason: the air was busy, packets waited up to %u ms"),
    (r"Причина: перевірка з порту", r"Reason: test from the port"),
    (r"Причина: на тому каналі радіо зупинялось", r"Reason: the radio kept stalling on that channel"),
    (r"Ефір зайнятий, вільнішого каналу немає", r"The air is busy, there is no freer channel"),
    (r"Лишаюсь на каналі %u (пакети чекали до %u мс)", r"Staying on channel %u (packets waited up to %u ms)"),
    # ---- устройство передатчика
    (r"знайдено", r"found"), (r"НЕ ЗНАЙДЕНО", r"NOT FOUND"), (r"увімкнено", r"on"), (r", іде запис", r", recording"),
    (r"Налаштування", r"Settings"),
    (r"Тиша ввімкнена з минулого разу — звук в ефір не йде", r"Mute is on since last time — no sound on air"),
    (r"Радіо перезапущено — ефір відновлено", r"Radio restarted — broadcast restored"),
    (r"Оновлення", r"Update"),
    (r"Оновити", r"Update"),
    (r"Пробне", r"Trial"),
    (r"На картці є прошивка %s.", r"Firmware %s is on the card."),
    (r"На картці та сама прошивка, що вже працює (%s).", r"The card has the firmware already running (%s)."),
    (r"У теці UPDATE на картці прошивки немає.", r"No firmware in the UPDATE folder on the card."),
    (r"Файл %s не годиться.", r"File %s is not usable."),
    (r"На картці старіша прошивка (%s) — не пропоную.", r"The card has older firmware (%s) — not offered."),
    (r"Картки пам'яті немає.", r"No memory card."),
    (r"Дивлюсь, що на картці…", r"Checking the card…"),
    (r"«Почати»: приймачам піде прошивка передавача (%s).", r"«Start»: receivers get the transmitter's firmware (%s)."),
    (r"Нова прошивка — файл .bin у теці UPDATE на картці.", r"New firmware: a .bin file in UPDATE on the card."),
    (r"Приймач, який уже має цю прошивку, нічого не робитиме.", r"A receiver that already has it does nothing."),
    (r"«Пробне» — показати, як це виглядає:", r"«Trial» shows how it looks:"),
    (r"приймачі приймуть прошивку, але не запишуть.", r"receivers take the firmware but do not write it."),
    (r"Передавач записує прошивку", r"Transmitter is writing firmware"),
    (r"Готово — передавач перезапускається", r"Done — transmitter is restarting"),
    (r"Не вдалося записати прошивку в передавач", r"Could not write firmware to the transmitter"),
    (r"Пробне оновлення пройшло — нічого не записано", r"Trial update done — nothing was written"),
    (r"Пробне: приймачі нічого не запишуть. Звук зупинено.", r"Trial: receivers write nothing. Sound paused."),
    (r"Звук уже в ефірі.", r"Sound is back on air."),
    (r"Не вимикайте передавач. Звук повернеться за хвилину.", r"Keep the transmitter on. Sound returns in a minute."),
    (r"Не вимикайте. Екран на час запису пригасає — так має бути.", r"Keep power on. The screen dims while writing — expected."),
    (r"Передавач оновлено: версія %s", r"Transmitter updated: version %s"),
    (r"Почати", r"Start"),
    (r"потрібна одна заливка по USB", r"needs one USB flash first"),
    (r"не почув передавача", r"lost the transmitter"),
    (r"скасовано", r"cancelled"),
    (r"оновлено — перезапускається", r"updated — restarting"),
    (r"уже має цю прошивку", r"already has this firmware"),
    (r"приймає: %d %%", r"receiving: %d %%"),
    (r"перевіряє", r"verifying"),
    (r"записує: %d %%", r"writing: %d %%"),
    (r"Оновлення приймачів", r"Receiver update"),
    (r"На цей час, близько хвилини, звук в ефірі зупиниться.", r"Sound on air stops meanwhile, for about a minute."),
    (r"Приймачі мають бути ввімкнені: сплячий не оновиться.", r"Receivers must be on: a sleeping one is skipped."),
    (r"оновлено", r"updated"),
    (r"прийняв і перевірив — не записував", r"received and verified — not written"),
    (r"Готую прошивку", r"Preparing firmware"),
    (r"Шукаю приймачі", r"Looking for receivers"),
    (r"Надсилаю прошивку", r"Sending firmware"),
    (r"Приймачі записують прошивку", r"Receivers are writing firmware"),
    (r"Завершено, але не всі оновились", r"Finished, but not all updated"),
    (r"Готово — приймачі оновлено", r"Done — receivers updated"),
    (r"Оновлювати нікого", r"Nothing to update"),
    (r"Жоден приймач не відповів", r"No receiver answered"),
    (r"Не вдалося прочитати прошивку", r"Could not read the firmware"),
    (r"Звук в ефірі зупинено до кінця передачі.", r"Sound on air is paused until sending ends."),
    (r"Звук уже в ефірі. Не вимикайте приймачі.", r"Sound is back on air. Keep receivers powered."),
    (r"і ще %d", r"and %d more"),
    (r"Чекаю відповіді приймачів", r"Waiting for receivers"),
    (r"Оновлення приймачів: оновлено %d, не вдалося %d", r"Receiver update: %d updated, %d failed"),
    (r"Оновлення приймачів: оновлювати нікого", r"Receiver update: nothing to update"),
    (r"Оновлення приймачів не завершено", r"Receiver update not finished"),
    (r"Оновлення зараз неможливе", r"Update is not possible right now"),
    (r"ОНОВЛЕННЯ", r"UPDATING"),
    (r"ПРОШИВКИ", r"FIRMWARE"),
    (r"ЗАРАЗ ОНОВИТЬСЯ", r"NOW UPDATING"),
    (r"ПЕРЕДАВАЧ", r"TRANSMITTER"),
    (r"ЕКРАН БЛИМАТИМЕ", r"SCREEN WILL BLINK"),
    (r"ТАК МАЄ БУТИ", r"THIS IS NORMAL"),
    (r"Прошивка: з %s на %s", r"Firmware: %s to %s"),
    (r"Запис триває близько хвилини. Не вимикайте живлення.", r"Writing takes about a minute. Keep the power on."),
    (r"Звуку в ефірі не буде до перезапуску передавача.", r"No sound on air until the transmitter restarts."),
    (r"Приймачі прошивку отримали (%d) і записують її самі.", r"Receivers got the firmware (%d) and write it themselves."),
    (r"Приймачі не відповіли — оновляться пізніше, від передавача.", r"No receivers answered — they update later from the transmitter."),
    (r"початок через %d с", r"starting in %d s"),
    (r"«Оновити»: спершу приймачі — по радіо, потім передавач.", r"«Update»: receivers first over the air, then the transmitter."),
    (r"Під час запису передавача екран блиматиме.", r"The screen blinks while the transmitter is written."),
    (r"НЕ ВИМИКАЙТЕ", r"DO NOT SWITCH"),
    (r"ЖИВЛЕННЯ!!!", r"POWER OFF!!!"),
    (r"ГОТОВО", r"DONE"),
    (r"ЕКРАН ЗГАСНЕ", r"SCREEN GOES DARK"),
    (r"НА ХВИЛИНУ", r"FOR A MINUTE"),
    (r"Прошивку записує комп'ютер кабелем — так має бути.", r"The computer writes the firmware over the cable — this is normal."),
    (r"Звук в ефір повернеться після перезапуску передавача.", r"Audio returns on air after the transmitter restarts."),
    (r"Оновлюю прошивку приймачів", r"Updating receiver firmware"),
    (r"близько хвилини — звук повернеться сам", r"about a minute — the sound returns by itself"),
    (r"ПЕРЕЗАПУСК", r"RESTARTING"),
    (r"екран на час запису пригасає — так має бути", r"the screen dims while writing — this is expected"),
    (r"прошивка %s", r"firmware %s"),
    (r"приймаю з передавача", r"receiving"),
    (r"перевіряю", r"verifying"),
    (r"записую, не вимикайте", r"writing, keep power on"),
    (r"готово, перезапуск", r"done, restarting"),
    (r"не вдалося", r"failed"),
    (r"потрібен USB (раз)", r"needs USB (once)"),
    (r"передавач зник", r"transmitter lost"),
    (r"помилка в даних", r"data error"),
    (r"забракло пам'яті", r"out of memory"),
    (r"помилка запису", r"write error"),
    (r"Мелодія %d", r"Tune %d"),
    (r"«%s» знову на зв'язку", r"«%s» is online again"), (r"«%s» на зв'язку", r"«%s» is online"), (r"«%s» зник зі зв'язку", r"«%s» went offline"),
    (r"На цій швидкості якість звуку — «%s»", r"At this rate the sound quality is «%s»"),
    (r"Швидкість %s Мбіт/с: якість буде «%s»", r"Rate %s Mbit/s: quality will be «%s»"),
    (r"Українська", r"Українська"),
    # ---- приёмник
    (r"Запас", r"Buffer"), (r"Виводи", r"Pins"), (r"Забути набір", r"Forget kit"), (r"Про пристрій", r"About"), (r"Вийти", r"Exit"),
    (r"авто (%u)", r"auto (%u)"), (r"сам (%.0f)", r"auto (%.0f)"),
    (r"2 канали", r"2 channels"), (r"протифаза", r"antiphase"), (r"нема ключа", r"no key"), (r"ТАК", r"YES"),
    (r"ЦЕ Я", r"IT'S ME"),
    # ---- приёмник, меню «для слуха и удобства» (2.32)
    (r"Вигляд", r"View"), (r"Світлодіод", r"LED"), (r"Мова", r"Language"), (r"Чіткість", r"Clarity"), (r"Баланс", r"Balance"),
    (r"Межа гучн.", r"Vol. limit"), (r"Навушники", r"Headphones"), (r"Зв'язок", r"Link"),
    (r"спектр", r"spectrum"), (r"стрілки", r"needles"), (r"гучність", r"volume"),
    (r"вимк.", r"off"), (r"тьмяно", r"dim"), (r"слабо", r"weak"), (r"норма", r"normal"), (r"яскраво", r"bright"),
    (r"як передавач", r"auto"), (r"українська", r"українська"),
    (r"легка", r"light"), (r"середня", r"medium"), (r"сильна", r"strong"),
    (r"1 канал", r"1 channel"), (r"рівно", r"centre"), (r"ліве +%d", r"left +%d"), (r"праве +%d", r"right +%d"),
    (r"тест", r"test"), (r"%d дБм", r"%d dBm"), (r"Межа гучності", r"Volume limit"), (r"Еквалайзер", r"Equalizer"), (r"Еквалайзер входу", r"Input equalizer"), (r"Блокування ручки", r"Knob lock"), (r"Підсилення", r"Boost"), (r"Підсилення гучності", r"Volume boost"), (r"меню", r"menu"), (r"усе", r"all"), (r"немає", r"none"),
    (r"Заблоковано", r"Locked"), (r"Розблоковано", r"Unlocked"),
    (r"Автооновлення: увімкнено", r"Auto-update: on"), (r"Автооновлення: вимкнено", r"Auto-update: off"), (r"Для всіх приймачів", r"For all receivers"), (r"Низ, 125 Гц", r"Bass, 125 Hz"), (r"400 Гц", r"400 Hz"),
    (r"1 кГц", r"1 kHz"), (r"2,5 кГц", r"2.5 kHz"), (r"Верх, 6 кГц", r"Treble, 6 kHz"), (r"Зріз низів, 100 Гц", r"Low cut, 100 Hz"),
    (r"Л", r"L"), (r"П", r"R"), (r"РІВЕНЬ", r"LEVEL"),
    (r"ЗВ'ЯЗОК", r"LINK"), (r"немає", r"none"), (r"відмінно", r"excellent"), (r"добре", r"good"), (r"помірно", r"fair"),
    (r"дБм", r"dBm"), (r"втр %.1f%%", r"loss %.1f%%"), (r"зап %.0fмс", r"buf %.0fms"),
    (r"Чіткість мови", r"Speech clarity"), (r"Вигляд екрана", r"Screen view"), (r"Мова написів", r"Language"), (r"два канали", r"two channels"),
    (r"як у передавача", r"as transmitter"), (r"Зупинити перевірку", r"Stop the test"), (r"Перевірка навушників", r"Headphone test"),
    (r"ПЕРЕВІРКА НАВУШНИКІВ", r"HEADPHONE TEST"), (r"обидва вуха", r"both ears"), (r"ліве вухо", r"left ear"), (r"праве вухо", r"right ear"),
    (r"набір %u  версія %s", r"kit %u  version %s"),
    (r"шукаю: канал", r"scanning: channel"), (r"канал", r"channel"),
    (r"Звук увімкнено", r"Sound on"),
    (r"Сигнал відновлено", r"Signal is back"),
    (r"Гучно на вході!", r"Input too loud!"),
    (r"Тиша в ефірі", r"Silence on air"),
    (r"Звук в ефірі", r"Sound on air"),
    (r"Слабкий сигнал", r"Weak signal"),
    (r"Вихід: стерео", r"Output: stereo"),
    (r"Вихід: моно", r"Output: mono"),
    (r"Нове ім'я приймача", r"Receiver renamed"),
    (r"Передавач на зв'язку", r"Transmitter found"),
    (r"ПОШУК ПЕРЕДАВАЧА", r"SEARCHING"),
    (r"НЕМАЄ СИГНАЛУ", r"NO SIGNAL"),
    (r"в.%s  К%u Н%u  %02X%02X%02X", r"v.%s  C%u K%u  %02X%02X%02X"),
    (r"запас %.1f мс", r"buffer %.1f ms"), (r"сигнал %d дБм", r"signal %d dBm"),
    (r"ЗАПУСК", r"STARTING"),
    (r"ВИМКНЕНО", r"TURNED OFF"),
    (r"з передавача", r"by transmitter"),
    (r"переходжу в сон", r"going to sleep"),
    (r"СИГНАЛ ВІДСУТНІЙ", r"SIGNAL LOST"),
    (r"переходжу у режим", r"switching to"),
    (r"очікування", r"standby mode"),
    (r"ручку двічі - увімк.", r"press knob twice: on"),
    (r"НЕ ПІДКЛЮЧЕНО", r"NOT CONNECTED"),
    (r"прошу доступ", r"asking for access"), (r"шукаю передавач", r"finding transmitter"),
    (r"прошу доступ...", r"asking for access..."), (r"шукаю передавач...", r"finding transmitter..."),
    (r"КОД %04u", r"CODE %04u"),
    (r"Приймачі - Додати", r"Receivers - Add"),
    (r"увімкніть передавач", r"switch transmitter on"),
    (r"Приймач %02X%02X", r"Receiver %02X%02X"),
]

# то, что переводить не надо: имя церкви и буквы экранной клавиатуры
KEEP = set(u"ВІДРОДЖЕННЯ й ц у к е н г ш щ з х ї ф і в а п р о л д ж є я ч с м и т ь б ю ґ".split())
